### 3. Load Ratings

In [15]:
df = pd.read_json('./ratings.json')
df

           userId                                             rating
0     [145704009]  [{'isbn': '1400341124', 'isbn13': '97814003411...
1       [8829118]  [{'isbn': '0812998626', 'isbn13': '97808129986...
2      [63113280]  [{'isbn': '', 'isbn13': '9781984829993', 'book...
3     [160270339]  [{'isbn': '0312642717', 'isbn13': '97803126427...
4     [103379996]  [{'isbn': '', 'isbn13': '', 'book_href': 'http...
...           ...                                                ...
1574  [107912421]  [{'isbn': '', 'isbn13': '', 'book_href': 'http...
1575  [167510184]  [{'isbn': '', 'isbn13': '', 'book_href': 'http...
1576   [92390881]  [{'isbn': '0525539727', 'isbn13': '97805255397...
1577   [63665211]  [{'isbn': '0063308312', 'isbn13': '97800633083...
1578  [125982174]  [{'isbn': '', 'isbn13': '', 'book_href': 'http...

[1579 rows x 2 columns]

In [17]:
exploded_df = df.explode('userId').reset_index(drop=True)
exploded_df = exploded_df.explode('rating').reset_index(drop=True)
exploded_df

           userId                                             rating
0       145704009  {'isbn': '1400341124', 'isbn13': '978140034112...
1       145704009  {'isbn': '1662527004', 'isbn13': '978166252700...
2       145704009  {'isbn': '1662529376', 'isbn13': '978166252937...
3       145704009  {'isbn': '1662529341', 'isbn13': '978166252934...
4       145704009  {'isbn': '166252823X', 'isbn13': '978166252823...
...           ...                                                ...
525779  125982174  {'isbn': '0439554934', 'isbn13': '978043955493...
525780  125982174  {'isbn': '0316015849', 'isbn13': '978031601584...
525781  125982174  {'isbn': '0062024035', 'isbn13': '978006202403...
525782  125982174  {'isbn': '', 'isbn13': '', 'book_href': 'https...
525783  125982174  {'isbn': '0439023483', 'isbn13': '978043902348...

[525784 rows x 2 columns]

In [19]:
expanded_df = pd.concat(
    [exploded_df.drop(columns='rating'), pd.json_normalize(exploded_df['rating'])],
    axis=1
)

In [20]:
expanded_df

,userId,isbn,isbn13,book_href,rating
0,145704009,1400341124,9781400341122,https://www.goodreads.com/book/show/200212922-...,5
1,145704009,1662527004,9781662527005,https://www.goodreads.com/book/show/219754771-...,4
2,145704009,1662529376,9781662529375,https://www.goodreads.com/book/show/220389090-...,4
3,145704009,1662529341,9781662529344,https://www.goodreads.com/book/show/220389457-...,4
4,145704009,166252823X,9781662528231,https://www.goodreads.com/book/show/220389455-...,3
...,...,...,...,...,...
525779,125982174,0439554934,9780439554930,https://www.goodreads.com/book/show/3.Harry_Po...,5
525780,125982174,0316015849,9780316015844,https://www.goodreads.com/book/show/41865.Twil...,5
525781,125982174,0062024035,9780062024039,https://www.goodreads.com/book/show/13335037-d...,5
525782,125982174,,,https://www.goodreads.com/book/show/11870085-t...,5
525783,125982174,0439023483,9780439023481,https://www.goodreads.com/book/show/2767052-th...,5

In [28]:
print(f"Unique ISBN_10: {expanded_df['isbn'].nunique()}, ISBN_13: {expanded_df['isbn13'].nunique()}")
print(f"Unique userId: {expanded_df['userId'].nunique()}")

Unique ISBN_10: 141192, ISBN_13: 143252
Unique userId: 1579