In [59]:
import polars as pl
import pandas as pd
from unidecode import unidecode

In [2]:
test = pl.read_csv('datalake/clean/books.csv')
test

shape: (102_561, 14)
┌────────────┬───────────┬──────────────┬──────────────┬───┬──────────────┬──────────────┬──────────────┬──────────────┐
│ isbn       ┆ isbn13    ┆ title        ┆ image_url    ┆ … ┆ publish_date ┆ crawl_source ┆ average_rati ┆ series       │
│ ---        ┆ ---       ┆ ---          ┆ ---          ┆   ┆ ---          ┆ ---          ┆ ng           ┆ ---          │
│ str        ┆ f64       ┆ str          ┆ str          ┆   ┆ str          ┆ str          ┆ ---          ┆ str          │
│            ┆           ┆              ┆              ┆   ┆              ┆              ┆ str          ┆              │
╞════════════╪═══════════╪══════════════╪══════════════╪═══╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 1662528396 ┆ 9.7817e12 ┆ ['Cruel      ┆ ['https://im ┆ … ┆ [17313984000 ┆ ['https://ww ┆ [3.71]       ┆ Under The    │
│            ┆           ┆ Winter with  ┆ ages-na.ssl- ┆   ┆ 00]          ┆ w.goodreads. ┆              ┆ Mistletoe    │
│            ┆           ┆ You']        ┆ images…      ┆   ┆              ┆ com/bo…      ┆              ┆ Collection   │
│ 0664266703 ┆ 9.7807e12 ┆ ['The        ┆ ['https://im ┆ … ┆ [16158780000 ┆ ['https://ww ┆ [4.13]       ┆ null         │
│            ┆           ┆ Purpose Gap: ┆ ages-na.ssl- ┆   ┆ 00]          ┆ w.goodreads. ┆              ┆              │
│            ┆           ┆ Empowering … ┆ images…      ┆   ┆              ┆ com/bo…      ┆              ┆              │
│ 166252823X ┆ 9.7817e12 ┆ ['All by My  ┆ ['https://im ┆ … ┆ [17313984000 ┆ ['https://ww ┆ [2.61]       ┆ Under The    │
│            ┆           ┆ Elf']        ┆ ages-na.ssl- ┆   ┆ 00]          ┆ w.goodreads. ┆              ┆ Mistletoe    │
│            ┆           ┆              ┆ images…      ┆   ┆              ┆ com/bo…      ┆              ┆ Collection   │
│ 1400341124 ┆ 9.7814e12 ┆ ['Mostly     ┆ ['https://im ┆ … ┆ [17084160000 ┆ ['https://ww ┆ [4.34]       ┆ null         │
│            ┆           ┆ What God     ┆ ages-na.ssl- ┆   ┆ 00]          ┆ w.goodreads. ┆              ┆              │
│            ┆           ┆ Does:        ┆ images…      ┆   ┆              ┆ com/bo…      ┆              ┆              │
│            ┆           ┆ Reflec…      ┆              ┆   ┆              ┆              ┆              ┆              │
│ 1662529376 ┆ 9.7817e12 ┆ ['Only       ┆ ['https://im ┆ … ┆ [17313984000 ┆ ['https://ww ┆ [3.39]       ┆ Under The    │
│            ┆           ┆ Santas in    ┆ ages-na.ssl- ┆   ┆ 00]          ┆ w.goodreads. ┆              ┆ Mistletoe    │
│            ┆           ┆ the          ┆ images…      ┆   ┆              ┆ com/bo…      ┆              ┆ Collection   │
│            ┆           ┆ Building'…   ┆              ┆   ┆              ┆              ┆              ┆              │
│ …          ┆ …         ┆ …            ┆ …            ┆ … ┆ …            ┆ …            ┆ …            ┆ …            │
│ 0226100316 ┆ 9.7802e12 ┆ ['Improvisin ┆ ['https://im ┆ … ┆ [11844828000 ┆ ['https://ww ┆ [4]          ┆ null         │
│            ┆           ┆ g Theory:    ┆ ages-na.ssl- ┆   ┆ 00]          ┆ w.goodreads. ┆              ┆              │
│            ┆           ┆ Process …    ┆ images…      ┆   ┆              ┆ com/bo…      ┆              ┆              │
│ 0451169530 ┆ 9.7805e12 ┆ null         ┆ null         ┆ … ┆ null         ┆ ['https://ww ┆ [4.35]       ┆ null         │
│            ┆           ┆              ┆              ┆   ┆              ┆ w.goodreads. ┆              ┆              │
│            ┆           ┆              ┆              ┆   ┆              ┆ com/bo…      ┆              ┆              │
│ 0140512691 ┆ 9.7801e12 ┆ ['The        ┆ ['https://im ┆ … ┆ [86247000000 ┆ ['https://ww ┆ [4]          ┆ null         │
│            ┆           ┆ Penguin      ┆ ages-na.ssl- ┆   ┆ 0]           ┆ w.goodreads. ┆              ┆              │
│            ┆           ┆ Dictionary   ┆ images…      ┆   ┆              ┆ com/bo…      ┆              ┆              │
│            ┆           ┆ of 19…       ┆              ┆   ┆              ┆              ┆              ┆              │
│ 0897332881 ┆ 9.7809e12 ┆ null         ┆ null         ┆ … ┆ null         ┆ ['https://ww ┆ [4.18]       ┆ null         │
│            ┆           ┆              ┆              ┆   ┆              ┆ w.goodreads. ┆              ┆              │
│            ┆           ┆              ┆              ┆   ┆              ┆ com/bo…      ┆              ┆              │
│ 0425090779 ┆ 9.7804e12 ┆ null         ┆ null         ┆ … ┆ null         ┆ ['https://ww ┆ [3.78]       ┆ null         │
│            ┆           ┆              ┆              ┆   ┆              ┆ w.goodreads. ┆              ┆              │
│            ┆           ┆              ┆              ┆   ┆              ┆ com/bo…      ┆              ┆              │
└────────────┴───────────┴──────────────┴──────────────┴───┴──────────────┴──────────────┴──────────────┴──────────────┘

In [5]:
hardcover_book_df = pl.read_csv('datalake/hardcover/hardcover_books.csv', schema={
    "id": pl.String,
    "ISBN_10": pl.String,
    "title": pl.String,
    "description": pl.String,
    "image_url": pl.String,
    "author": pl.String,
    "language": pl.String,
    "publish_date": pl.String,
    "num_pages": pl.UInt64,
    "crawl_source": pl.String
})
hardcover_book_df

shape: (193_441, 10)
┌───────────────┬────────────┬────────────────┬───────────────┬───┬──────────┬──────────────┬───────────┬──────────────┐
│ id            ┆ ISBN_10    ┆ title          ┆ description   ┆ … ┆ language ┆ publish_date ┆ num_pages ┆ crawl_source │
│ ---           ┆ ---        ┆ ---            ┆ ---           ┆   ┆ ---      ┆ ---          ┆ ---       ┆ ---          │
│ str           ┆ str        ┆ str            ┆ str           ┆   ┆ str      ┆ str          ┆ u64       ┆ str          │
╞═══════════════╪════════════╪════════════════╪═══════════════╪═══╪══════════╪══════════════╪═══════════╪══════════════╡
│ 9780713469875 ┆ 0713469870 ┆ Pattern        ┆ null          ┆ … ┆ English  ┆ 1993-07-01   ┆ 184       ┆ hardcover    │
│               ┆            ┆ Drafting for   ┆               ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆ Dressmaki…     ┆               ┆   ┆          ┆              ┆           ┆              │
│ 9781776563531 ┆ 1776563530 ┆ Head Girl      ┆ 'The first    ┆ … ┆ English  ┆ 2020-01-01   ┆ 107       ┆ hardcover    │
│               ┆            ┆                ┆ time I read   ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆                ┆ Freya’s…      ┆   ┆          ┆              ┆           ┆              │
│ 9780811218832 ┆ 081121883X ┆ Everything and ┆ A             ┆ … ┆ English  ┆ 1999-04-01   ┆ 129       ┆ hardcover    │
│               ┆            ┆ Nothing        ┆ pocket-sized  ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆                ┆ Pearls        ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆                ┆ edition …     ┆   ┆          ┆              ┆           ┆              │
│ 9780450054594 ┆ 0450054594 ┆ Cat's Revenge: ┆ null          ┆ … ┆ English  ┆ 1981-01-01   ┆ 98        ┆ hardcover    │
│               ┆            ┆ More Than 101  ┆               ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆ U…             ┆               ┆   ┆          ┆              ┆           ┆              │
│ 9781607051978 ┆ 1607051974 ┆ Block Party -  ┆ null          ┆ … ┆ null     ┆ 2011-05-01   ┆ 0         ┆ hardcover    │
│               ┆            ┆ The Modern     ┆               ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆ Quilt…         ┆               ┆   ┆          ┆              ┆           ┆              │
│ …             ┆ …          ┆ …              ┆ …             ┆ … ┆ …        ┆ …            ┆ …         ┆ …            │
│ 9780521379656 ┆ 0521379652 ┆ The Neglect of ┆ null          ┆ … ┆ English  ┆ 1986-01-01   ┆ 304       ┆ hardcover    │
│               ┆            ┆ Experiment     ┆               ┆   ┆          ┆              ┆           ┆              │
│ 9781910281970 ┆ 1910281972 ┆ Cabin          ┆ null          ┆ … ┆ English  ┆ 2015-01-15   ┆ 0         ┆ hardcover    │
│               ┆            ┆ Pressure:      ┆               ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆ Zurich         ┆               ┆   ┆          ┆              ┆           ┆              │
│ 9780307460455 ┆ 0307460452 ┆ Change we can  ┆ Outlines      ┆ … ┆ null     ┆ 2008-01-01   ┆ 273       ┆ hardcover    │
│               ┆            ┆ believe in     ┆ Obama's plan  ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆                ┆ to effec…     ┆   ┆          ┆              ┆           ┆              │
│ 9781250366788 ┆ 125036678X ┆ The Romantic   ┆ Heartstopper  ┆ … ┆ English  ┆ 2025-01-28   ┆ 0         ┆ hardcover    │
│               ┆            ┆ Tragedies of a ┆ meets Derry   ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆ Dr…            ┆ Girls…        ┆   ┆          ┆              ┆           ┆              │
│ 9781788166560 ┆ null       ┆ Boys and Sex   ┆ The New York  ┆ … ┆ English  ┆ 2020-01-01   ┆ 304       ┆ hardcover    │
│               ┆            ┆ Young Men on   ┆ Times         ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆ Hook…          ┆ Bestseller …  ┆   ┆          ┆              ┆           ┆              │
└───────────────┴────────────┴────────────────┴───────────────┴───┴──────────┴──────────────┴───────────┴──────────────┘

In [6]:
hardcover_genre_df = pl.read_csv('datalake/hardcover/hardcover_book_genre.csv', schema={
    "id": pl.String,
    "genre": pl.String,
})
hardcover_genre_df

shape: (285_813, 2)
┌───────────────┬──────────────────────┐
│ id            ┆ genre                │
│ ---           ┆ ---                  │
│ str           ┆ str                  │
╞═══════════════╪══════════════════════╡
│ 9781776563531 ┆ Young Adult          │
│ 9781776563531 ┆ Poetry               │
│ 9780811218832 ┆ Classics             │
│ 9780811218832 ┆ Literary Collections │
│ 9780450054594 ┆ Comics               │
│ …             ┆ …                    │
│ 9780307460455 ┆ Politics             │
│ 9781250366788 ┆ Young Adult          │
│ 9781250366788 ┆ LGBTQ                │
│ 9781250366788 ┆ Young Adult Fiction  │
│ 9781788166560 ┆ LGBTQ                │
└───────────────┴──────────────────────┘

In [12]:
goodreads_genre_df = pl.read_csv('datalake/clean/genres.csv').rename({"name":"genre"})
goodreads_genre_df

shape: (1_022, 2)
┌──────────┬────────────────────┐
│ genre_id ┆ genre              │
│ ---      ┆ ---                │
│ i64      ┆ str                │
╞══════════╪════════════════════╡
│ 1        ┆ 14th Century       │
│ 2        ┆ Southern           │
│ 3        ┆ Agriculture        │
│ 4        ┆ Australia          │
│ 5        ┆ Mormonism          │
│ …        ┆ …                  │
│ 1018     ┆ Basketball         │
│ 1019     ┆ Witches            │
│ 1020     ┆ Native American    │
│ 1021     ┆ African Literature │
│ 1022     ┆ Multiplication     │
└──────────┴────────────────────┘

In [29]:
merged_genres = pl.concat([
    goodreads_genre_df.select("genre"),
    hardcover_genre_df.select("genre")
], how="vertical_relaxed")

merged_genres = merged_genres.unique()
merged_genres

shape: (6_905, 1)
┌──────────────────────────────┐
│ genre                        │
│ ---                          │
│ str                          │
╞══════════════════════════════╡
│ Glück                        │
│ Cabala                       │
│ Asymmetric warfare           │
│ Children's stories, German   │
│ Justice                      │
│ …                            │
│ Artists' preparatory studies │
│ Mythology, Roman             │
│ Hindi language               │
│ Anger                        │
│  Dien Bien Phu               │
└──────────────────────────────┘

In [72]:
merged_genres_stripped = merged_genres.with_columns(
    merged_genres['genre']
    .str.split(",")
    .list.eval(pl.element().str.strip_chars())
    .alias('split_genres')
).explode('split_genres').select('split_genres').unique()
merged_genres_stripped

shape: (6_370, 1)
┌─────────────────────────────────┐
│ split_genres                    │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ Amnesia                         │
│ Guyana                          │
│ Post Colonial                   │
│ Cincinnati (Ohio)               │
│ Camino de Santiago de Composte… │
│ …                               │
│ Stress management               │
│ 12th Century                    │
│ Qi (Chinese philosophy)         │
│ Presidents                      │
│ Human engineering               │
└─────────────────────────────────┘

In [ ]:
.str.to_lowercase().str.replace(" ", "-").str.slice(0,15)

In [104]:
merged_genres_cleaned = merged_genres_stripped.with_columns(
    pl.col('split_genres')
    .map_elements(unidecode, return_dtype=pl.String)  # Apply unidecode
    .str.to_lowercase()
    .str.replace_all(r"[&'()+\-./:\[\]?`]", "")
    .str.replace(" ", "-")
    .str.slice(0,15)
    .alias("tag_genres")
)
merged_genres_cleaned

shape: (6_370, 2)
┌─────────────────────────────────┬─────────────────┐
│ split_genres                    ┆ tag_genres      │
│ ---                             ┆ ---             │
│ str                             ┆ str             │
╞═════════════════════════════════╪═════════════════╡
│ Amnesia                         ┆ amnesia         │
│ Guyana                          ┆ guyana          │
│ Post Colonial                   ┆ post-colonial   │
│ Cincinnati (Ohio)               ┆ cincinnati-ohio │
│ Camino de Santiago de Composte… ┆ camino-de santi │
│ …                               ┆ …               │
│ Stress management               ┆ stress-manageme │
│ 12th Century                    ┆ 12th-century    │
│ Qi (Chinese philosophy)         ┆ qi-chinese phil │
│ Presidents                      ┆ presidents      │
│ Human engineering               ┆ human-engineeri │
└─────────────────────────────────┴─────────────────┘

In [105]:
unique_chars = set(''.join(merged_genres_cleaned['tag_genres']))
print("Unique Characters:")
print(sorted(unique_chars))

Unique Characters:
[' ', '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

In [82]:
unique_chars = (
    merged_genres_stripped
    .select(pl.col("tag_genres").str.concat(delimiter=""))  # Concatenate all strings
    .unique()  # Get unique characters
)

print(sorted(set(unique_chars.item())))

ColumnNotFoundError: tag_genres

### 2. Users

In [47]:
hardcover_user_df = pl.read_csv('datalake/hardcover/hardcover_users.csv').rename({
    'name':'full_name', 'id':'userid_source'
})

# Add source column
hardcover_user_df = hardcover_user_df.with_columns(
    pl.lit('hardcover').alias('account_source')
)

hardcover_user_df

shape: (21_336, 5)
┌───────────────┬───────────────────┬─────────────────┬─────────────┬────────────────┐
│ userid_source ┆ full_name         ┆ username        ┆ books_count ┆ account_source │
│ ---           ┆ ---               ┆ ---             ┆ ---         ┆ ---            │
│ i64           ┆ str               ┆ str             ┆ i64         ┆ str            │
╞═══════════════╪═══════════════════╪═════════════════╪═════════════╪════════════════╡
│ 18783         ┆ Nitin Rughoonauth ┆ Nitin           ┆ 7951        ┆ hardcover      │
│ 22985         ┆ Court             ┆ Courtreader     ┆ 7474        ┆ hardcover      │
│ 19573         ┆ Martha            ┆ Martha          ┆ 6933        ┆ hardcover      │
│ 13481         ┆ Deb Nance         ┆ DebNance        ┆ 6773        ┆ hardcover      │
│ 13318         ┆ abi               ┆ booksgamesvinyl ┆ 5666        ┆ hardcover      │
│ …             ┆ …                 ┆ …               ┆ …           ┆ …              │
│ 16898         ┆ Yaiza             ┆ Yai002          ┆ 0           ┆ hardcover      │
│ 14087         ┆ Stacy             ┆ Tacy_0301       ┆ 0           ┆ hardcover      │
│ 2609          ┆ Thomas Bartensud  ┆ bartensud       ┆ 0           ┆ hardcover      │
│ 19784         ┆ null              ┆ null            ┆ 0           ┆ hardcover      │
│ 16559         ┆ Mauro             ┆ maurocamara     ┆ 0           ┆ hardcover      │
└───────────────┴───────────────────┴─────────────────┴─────────────┴────────────────┘

In [48]:
goodreads_user_df = pl.read_csv('datalake/clean/users.csv').rename({
    'name':'full_name','user_id':'userid_source'
})

goodreads_user_df = goodreads_user_df.with_columns(
    pl.lit('goodreads').alias('account_source')
)

goodreads_user_df

shape: (23_592, 8)
┌───────────────┬──────────────┬──────────────┬──────────────┬──────────────┬────────────┬──────────────┬──────────────┐
│ userid_source ┆ full_name    ┆ profile_url  ┆ total_rating ┆ total_review ┆ avg_rating ┆ image_url    ┆ account_sour │
│ ---           ┆ ---          ┆ ---          ┆ s            ┆ s            ┆ ---        ┆ ---          ┆ ce           │
│ i64           ┆ str          ┆ str          ┆ ---          ┆ ---          ┆ f64        ┆ str          ┆ ---          │
│               ┆              ┆              ┆ i64          ┆ i64          ┆            ┆              ┆ str          │
╞═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪════════════╪══════════════╪══════════════╡
│ 19185877      ┆ acacia       ┆ https://www. ┆ 835          ┆ 59           ┆ 4.3        ┆ https://imag ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆ es.gr-assets ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆ .com/u…      ┆              │
│ 169105231     ┆ kelli        ┆ https://www. ┆ 384          ┆ 1            ┆ 3.6        ┆ https://imag ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆ es.gr-assets ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆ .com/u…      ┆              │
│ 38623456      ┆ steph        ┆ https://www. ┆ 365          ┆ 0            ┆ 3.33       ┆ https://s.gr ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆ -assets.com/ ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆ assets…      ┆              │
│ 8829118       ┆ mindy        ┆ https://www. ┆ 59           ┆ 2            ┆ 3.69       ┆ null         ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆              ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆              ┆              │
│ 179297432     ┆ kourtney     ┆ https://www. ┆ 64           ┆ 11           ┆ 4.28       ┆ null         ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆              ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆              ┆              │
│ …             ┆ …            ┆ …            ┆ …            ┆ …            ┆ …          ┆ …            ┆ …            │
│ 502678        ┆ Gail         ┆ https://www. ┆ 0            ┆ 0            ┆ 0.0        ┆ https://i.gr ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆ -assets.com/ ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆ images…      ┆              │
│ 31968163      ┆ The          ┆ https://www. ┆ 0            ┆ 0            ┆ 0.0        ┆ https://i.gr ┆ goodreads    │
│               ┆ Overflowing  ┆ goodreads.co ┆              ┆              ┆            ┆ -assets.com/ ┆              │
│               ┆ Inkwell      ┆ m/user…      ┆              ┆              ┆            ┆ images…      ┆              │
│ 43122073      ┆ Linda        ┆ https://www. ┆ 0            ┆ 0            ┆ 0.0        ┆ https://i.gr ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆ -assets.com/ ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆ images…      ┆              │
│ 87271128      ┆ Khava        ┆ https://www. ┆ 0            ┆ 0            ┆ 0.0        ┆ https://i.gr ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆ -assets.com/ ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆ images…      ┆              │
│ 129029151     ┆ Her Half     ┆ https://www. ┆ 0            ┆ 0            ┆ 0.0        ┆ null         ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆              ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆              ┆              │
└───────────────┴──────────────┴──────────────┴──────────────┴──────────────┴────────────┴──────────────┴──────────────┘

In [49]:
merged_users = pl.concat([
    goodreads_user_df.select(["full_name","account_source","userid_source"]),
    hardcover_user_df.select(["full_name","account_source","userid_source"])   
], how="vertical_relaxed")

In [58]:
print(merged_users)
print(merged_users.drop_nulls())

shape: (44_928, 3)
┌──────────────────┬────────────────┬───────────────┐
│ full_name        ┆ account_source ┆ userid_source │
│ ---              ┆ ---            ┆ ---           │
│ str              ┆ str            ┆ i64           │
╞══════════════════╪════════════════╪═══════════════╡
│ acacia           ┆ goodreads      ┆ 19185877      │
│ kelli            ┆ goodreads      ┆ 169105231     │
│ steph            ┆ goodreads      ┆ 38623456      │
│ mindy            ┆ goodreads      ┆ 8829118       │
│ kourtney         ┆ goodreads      ┆ 179297432     │
│ …                ┆ …              ┆ …             │
│ Yaiza            ┆ hardcover      ┆ 16898         │
│ Stacy            ┆ hardcover      ┆ 14087         │
│ Thomas Bartensud ┆ hardcover      ┆ 2609          │
│ null             ┆ hardcover      ┆ 19784         │
│ Mauro            ┆ hardcover      ┆ 16559         │
└──────────────────┴────────────────┴───────────────┘
shape: (44_476, 3)
┌──────────────────┬────────────────┬───────────────┐
│ full_name        ┆ account_source ┆ userid_source │
│ ---              ┆ ---            ┆ ---           │
│ str              ┆ str            ┆ i64           │
╞══════════════════╪════════════════╪═══════════════╡
│ acacia           ┆ goodreads      ┆ 19185877      │
│ kelli            ┆ goodreads      ┆ 169105231     │
│ steph            ┆ goodreads      ┆ 38623456      │
│ mindy            ┆ goodreads      ┆ 8829118       │
│ kourtney         ┆ goodreads      ┆ 179297432     │
│ …                ┆ …              ┆ …             │
│ Angela           ┆ hardcover      ┆ 2746          │
│ Yaiza            ┆ hardcover      ┆ 16898         │
│ Stacy            ┆ hardcover      ┆ 14087         │
│ Thomas Bartensud ┆ hardcover      ┆ 2609          │
│ Mauro            ┆ hardcover      ┆ 16559         │
└──────────────────┴────────────────┴───────────────┘

In [56]:
merged_users.drop_nulls().write_csv('datalake/clean_merge/users.csv')

In [57]:
all_user_df = pl.read_csv('datalake/clean_merge/users.csv')
all_user_df

shape: (44_476, 3)
┌──────────────────┬────────────────┬───────────────┐
│ full_name        ┆ account_source ┆ userid_source │
│ ---              ┆ ---            ┆ ---           │
│ str              ┆ str            ┆ i64           │
╞══════════════════╪════════════════╪═══════════════╡
│ acacia           ┆ goodreads      ┆ 19185877      │
│ kelli            ┆ goodreads      ┆ 169105231     │
│ steph            ┆ goodreads      ┆ 38623456      │
│ mindy            ┆ goodreads      ┆ 8829118       │
│ kourtney         ┆ goodreads      ┆ 179297432     │
│ …                ┆ …              ┆ …             │
│ Angela           ┆ hardcover      ┆ 2746          │
│ Yaiza            ┆ hardcover      ┆ 16898         │
│ Stacy            ┆ hardcover      ┆ 14087         │
│ Thomas Bartensud ┆ hardcover      ┆ 2609          │
│ Mauro            ┆ hardcover      ┆ 16559         │
└──────────────────┴────────────────┴───────────────┘