In [1]:
import gdown
id = "1LfAv_C1biyjBNCjq8i5H_aAiKZX6Wy39"
output = "./datalake/"
gdown.download_folder(id=id, output=output)

Retrieving folder contents

Retrieving folder 1gyLmWrn1cXerpHt3zJK6bnW5XLEISk9O goodreads
Retrieving folder 13990kVlfyeCWKKfCFFexUUCvunwAxijr idk
Processing file 1W9j9BrbBft2YlUV7LqkcT7VmiI9_S-f9 all_reviews.json
Processing file 1GfQfIMRZTs_Zks5YccKv_59jtmu0ZSxx data.json
Processing file 11-ZxEKy0qQmjnK2GX8xrBN0VyfgDcWd4 book_1_10k.json
Processing file 1r6KLxRYF-l8YDsdgmN-Qx5KBuW1WWkB9 books_200000_to_250000.json
Processing file 13CGqL0yvKpqmk252tHc8gx5VT_SpnQIO data_50000_60000.json
Processing file 18lFGVnEDrkHLbEW-ILFBAhsbaZzI9hBY data_60001_70000.json
Processing file 1sClK93hrh5vzVoRG9MWqK9pLSKh5zes8 data_70001_80000.json
Processing file 1ANynEy3pdUJ0T1HA_K70sYgq5UtLTiEP data_80001_90000.json
Processing file 1BVN8UykiAj_3P2qv2caDpkO-rEgFefdR data_review1_10k.json
Processing file 1HsmcnNaZ8fpBY2jUHYlS2taV8SDc_jHT data_review150-155k.json
Processing file 1k1W1SIpB-zaNWvgn1gSrLfRPnNqO_69w data_review155-160k.json
Processing file 14nLLgzN7HWEHS8Zt0nNcRgC7DTA7PsUB data_review160-165k.json
Processing file 1xGj0xU9WyqFS2dJFsm92LX-BBXYuPdIb data_review165-170k.json
Processing file 1FbXKzPVfTPje_27p77VGawGuDBRE0fsF data_review170-175k.json
Processing file 1AgN5ld59S5nKfdpmFeKSasrEx_WHXbUx group_user.json
Processing file 1fz_ga6yXVEB5PVWXyGEmLTt530QeP07e group1.json
Processing file 12xa3Zv7v5DU4sw5nE62aIlZMx7ZT4HJu review_50000_60000.json
Processing file 1Ee8dfH-A_dxGgPEPSTGgirhi1fkQ3zuc reviews_books_200000_to_250000.json
Processing file 1rHcxDYbt3I3aZk-wKZkwszKZyZcHkPBk reviews.jsonl
Processing file 1-8shdA38ljgvEJo5pxe-2aBmCJrV3IU_ users.jsonl
Retrieving folder 1UbohrgXZmytUTeXkUkdeGQ0oG1eB7XWS hardcover
Processing file 1-PxNCybIuhn4iGldP5B2Nd26F2uxNspV hardcover_rating_1-200000.json
Processing file 12iwn45MjAmluW0Qc4RhF7fWBqdw5i2bv hardcover_rating_200001-400000.json
Processing file 1urZjdiYXjhspoSUZX1xXyVFNe35fE-Lz hardcover_rating_400001-600000.json
Processing file 1AWzuyVN0hPe6xkS8FERjYjkv368IRWxn hardcover_rating_600001-800000.json
Processing file 1h7b3pSh_LcGgHSFDMQvBu1EFI2Bopugc hardcover_rating_800001-1000000.json
Processing file 1Lqc7l7iIZ9EXKqXF8BtsbqfhcOSj4Azq hardcover_rating_1000001-1200000.json
Processing file 1rTsCcYxeD6_CJhPxoq2V-b567oKJMkuC hardcover_rating_1200001-1400000.json
Processing file 11gCz-1IcFmz6EECeWEqVv9PaKLHjdX_j hardcover_rating_1400001-1600000.json
Processing file 1t7w9rxsbka16J7mw5k02pxXEc3jQy2ea hardcover_rating_1600001-1631000.json

Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1W9j9BrbBft2YlUV7LqkcT7VmiI9_S-f9
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\idk\all_reviews.json
100%|█████████████████████████████████████████████████████████████████████████████| 3.81M/3.81M [00:00<00:00, 8.11MB/s]
Downloading...
From: https://drive.google.com/uc?id=1GfQfIMRZTs_Zks5YccKv_59jtmu0ZSxx
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\idk\data.json
100%|██████████████████████████████████████████████████████████████████████████████| 1.06M/1.06M [00:01<00:00, 799kB/s]
Downloading...
From: https://drive.google.com/uc?id=11-ZxEKy0qQmjnK2GX8xrBN0VyfgDcWd4
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\book_1_10k.json
100%|█████████████████████████████████████████████████████████████████████████████| 9.65M/9.65M [00:01<00:00, 9.09MB/s]
Downloading...
From: https://drive.google.com/uc?id=1r6KLxRYF-l8YDsdgmN-Qx5KBuW1WWkB9
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\books_200000_to_250000.json
100%|█████████████████████████████████████████████████████████████████████████████| 44.4M/44.4M [00:04<00:00, 10.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=13CGqL0yvKpqmk252tHc8gx5VT_SpnQIO
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\data_50000_60000.json
100%|█████████████████████████████████████████████████████████████████████████████| 9.23M/9.23M [00:01<00:00, 8.13MB/s]
Downloading...
From: https://drive.google.com/uc?id=18lFGVnEDrkHLbEW-ILFBAhsbaZzI9hBY
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\data_60001_70000.json
100%|█████████████████████████████████████████████████████████████████████████████| 8.69M/8.69M [00:00<00:00, 9.48MB/s]
Downloading...
From: https://drive.google.com/uc?id=1sClK93hrh5vzVoRG9MWqK9pLSKh5zes8
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\data_70001_80000.json
100%|█████████████████████████████████████████████████████████████████████████████| 9.16M/9.16M [00:01<00:00, 9.06MB/s]
Downloading...
From: https://drive.google.com/uc?id=1ANynEy3pdUJ0T1HA_K70sYgq5UtLTiEP
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\data_80001_90000.json
100%|█████████████████████████████████████████████████████████████████████████████| 9.98M/9.98M [00:05<00:00, 1.89MB/s]
Downloading...
From: https://drive.google.com/uc?id=1BVN8UykiAj_3P2qv2caDpkO-rEgFefdR
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\data_review1_10k.json
100%|█████████████████████████████████████████████████████████████████████████████| 4.93M/4.93M [00:00<00:00, 5.02MB/s]
Downloading...
From: https://drive.google.com/uc?id=1HsmcnNaZ8fpBY2jUHYlS2taV8SDc_jHT
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\data_review150-155k.json
100%|█████████████████████████████████████████████████████████████████████████████| 1.26M/1.26M [00:00<00:00, 5.20MB/s]
Downloading...
From: https://drive.google.com/uc?id=1k1W1SIpB-zaNWvgn1gSrLfRPnNqO_69w
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\data_review155-160k.json
100%|█████████████████████████████████████████████████████████████████████████████| 1.82M/1.82M [00:00<00:00, 5.93MB/s]
Downloading...
From: https://drive.google.com/uc?id=14nLLgzN7HWEHS8Zt0nNcRgC7DTA7PsUB
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\data_review160-165k.json
100%|█████████████████████████████████████████████████████████████████████████████| 1.76M/1.76M [00:00<00:00, 5.64MB/s]
Downloading...
From: https://drive.google.com/uc?id=1xGj0xU9WyqFS2dJFsm92LX-BBXYuPdIb
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\data_review165-170k.json
100%|█████████████████████████████████████████████████████████████████████████████| 1.71M/1.71M [00:00<00:00, 6.09MB/s]
Downloading...
From: https://drive.google.com/uc?id=1FbXKzPVfTPje_27p77VGawGuDBRE0fsF
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\data_review170-175k.json
100%|█████████████████████████████████████████████████████████████████████████████| 1.71M/1.71M [00:00<00:00, 5.78MB/s]
Downloading...
From: https://drive.google.com/uc?id=1AgN5ld59S5nKfdpmFeKSasrEx_WHXbUx
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\group_user.json
100%|█████████████████████████████████████████████████████████████████████████████| 1.03M/1.03M [00:00<00:00, 4.23MB/s]
Downloading...
From: https://drive.google.com/uc?id=1fz_ga6yXVEB5PVWXyGEmLTt530QeP07e
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\group1.json
100%|███████████████████████████████████████████████████████████████████████████████| 396k/396k [00:00<00:00, 2.30MB/s]
Downloading...
From: https://drive.google.com/uc?id=12xa3Zv7v5DU4sw5nE62aIlZMx7ZT4HJu
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\review_50000_60000.json
100%|█████████████████████████████████████████████████████████████████████████████| 4.50M/4.50M [00:01<00:00, 2.56MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Ee8dfH-A_dxGgPEPSTGgirhi1fkQ3zuc
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\reviews_books_200000_to_250000.json
100%|█████████████████████████████████████████████████████████████████████████████| 5.15M/5.15M [00:00<00:00, 8.03MB/s]
Downloading...
From: https://drive.google.com/uc?id=1rHcxDYbt3I3aZk-wKZkwszKZyZcHkPBk
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\reviews.jsonl
100%|███████████████████████████████████████████████████████████████████████████████| 452k/452k [00:00<00:00, 2.63MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-8shdA38ljgvEJo5pxe-2aBmCJrV3IU_
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\goodreads\users.jsonl
100%|█████████████████████████████████████████████████████████████████████████████| 6.14M/6.14M [00:01<00:00, 5.04MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-PxNCybIuhn4iGldP5B2Nd26F2uxNspV
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\hardcover\hardcover_rating_1-200000.json
100%|█████████████████████████████████████████████████████████████████████████████| 27.6M/27.6M [00:02<00:00, 9.39MB/s]
Downloading...
From: https://drive.google.com/uc?id=12iwn45MjAmluW0Qc4RhF7fWBqdw5i2bv
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\hardcover\hardcover_rating_200001-400000.json
100%|█████████████████████████████████████████████████████████████████████████████| 27.6M/27.6M [00:03<00:00, 8.69MB/s]
Downloading...
From: https://drive.google.com/uc?id=1urZjdiYXjhspoSUZX1xXyVFNe35fE-Lz
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\hardcover\hardcover_rating_400001-600000.json
100%|█████████████████████████████████████████████████████████████████████████████| 27.6M/27.6M [00:03<00:00, 8.64MB/s]
Downloading...
From: https://drive.google.com/uc?id=1AWzuyVN0hPe6xkS8FERjYjkv368IRWxn
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\hardcover\hardcover_rating_600001-800000.json
100%|█████████████████████████████████████████████████████████████████████████████| 27.7M/27.7M [00:03<00:00, 7.70MB/s]
Downloading...
From: https://drive.google.com/uc?id=1h7b3pSh_LcGgHSFDMQvBu1EFI2Bopugc
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\hardcover\hardcover_rating_800001-1000000.json
100%|█████████████████████████████████████████████████████████████████████████████| 27.7M/27.7M [00:03<00:00, 8.76MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Lqc7l7iIZ9EXKqXF8BtsbqfhcOSj4Azq
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\hardcover\hardcover_rating_1000001-1200000.json
100%|█████████████████████████████████████████████████████████████████████████████| 27.7M/27.7M [00:03<00:00, 7.61MB/s]
Downloading...
From: https://drive.google.com/uc?id=1rTsCcYxeD6_CJhPxoq2V-b567oKJMkuC
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\hardcover\hardcover_rating_1200001-1400000.json
100%|█████████████████████████████████████████████████████████████████████████████| 27.7M/27.7M [00:02<00:00, 9.98MB/s]
Downloading...
From: https://drive.google.com/uc?id=11gCz-1IcFmz6EECeWEqVv9PaKLHjdX_j
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\hardcover\hardcover_rating_1400001-1600000.json
100%|█████████████████████████████████████████████████████████████████████████████| 27.7M/27.7M [00:02<00:00, 11.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1t7w9rxsbka16J7mw5k02pxXEc3jQy2ea
To: D:\Development\Projects\book-rec-2\data-pipeline\datalake\hardcover\hardcover_rating_1600001-1631000.json
100%|█████████████████████████████████████████████████████████████████████████████| 4.35M/4.35M [00:00<00:00, 7.53MB/s]
Download completed

['./datalake/goodreads\\idk\\all_reviews.json',
 './datalake/goodreads\\idk\\data.json',
 './datalake/goodreads\\book_1_10k.json',
 './datalake/goodreads\\books_200000_to_250000.json',
 './datalake/goodreads\\data_50000_60000.json',
 './datalake/goodreads\\data_60001_70000.json',
 './datalake/goodreads\\data_70001_80000.json',
 './datalake/goodreads\\data_80001_90000.json',
 './datalake/goodreads\\data_review1_10k.json',
 './datalake/goodreads\\data_review150-155k.json',
 './datalake/goodreads\\data_review155-160k.json',
 './datalake/goodreads\\data_review160-165k.json',
 './datalake/goodreads\\data_review165-170k.json',
 './datalake/goodreads\\data_review170-175k.json',
 './datalake/goodreads\\group_user.json',
 './datalake/goodreads\\group1.json',
 './datalake/goodreads\\review_50000_60000.json',
 './datalake/goodreads\\reviews_books_200000_to_250000.json',
 './datalake/goodreads\\reviews.jsonl',
 './datalake/goodreads\\users.jsonl',
 './datalake/hardcover\\hardcover_rating_1-200000.json',
 './datalake/hardcover\\hardcover_rating_200001-400000.json',
 './datalake/hardcover\\hardcover_rating_400001-600000.json',
 './datalake/hardcover\\hardcover_rating_600001-800000.json',
 './datalake/hardcover\\hardcover_rating_800001-1000000.json',
 './datalake/hardcover\\hardcover_rating_1000001-1200000.json',
 './datalake/hardcover\\hardcover_rating_1200001-1400000.json',
 './datalake/hardcover\\hardcover_rating_1400001-1600000.json',
 './datalake/hardcover\\hardcover_rating_1600001-1631000.json']

In [1]:
import pandas as pd

In [4]:
df = pd.read_json('./datalake/goodreads/group_user.json')
df

,userId,name,profileUrl,totalRatings,totalReviews,avgRating,imageUrl
0,[19185877],[acacia],[https://www.goodreads.com/user/show/19185877-...,[835],[59],[4.30],[https://images.gr-assets.com/users/1597698907...
1,[169105231],[kelli],[https://www.goodreads.com/user/show/169105231...,[384],[1],[3.60],[https://images.gr-assets.com/users/1692562817...
2,[38623456],[steph],[https://www.goodreads.com/user/show/38623456-...,[365],[0],[3.33],[https://s.gr-assets.com/assets/nophoto/user/f...
3,[8829118],[mindy],[https://www.goodreads.com/user/show/8829118-m...,[59],[2],[3.69],NaN
4,[179297432],[kourtney],[https://www.goodreads.com/user/show/179297432...,[64],[11],[4.28],NaN
...,...,...,...,...,...,...,...
4431,[53365380],[malou],[https://www.goodreads.com/user/show/53365380-...,[205],[0],[4.12],[https://s.gr-assets.com/assets/nophoto/user/u...
4432,[59821420],[lisa],[https://www.goodreads.com/user/show/59821420-...,[262],[449],[3.11],[https://images.gr-assets.com/users/1734004183...
4433,[38322134],[valree],[https://www.goodreads.com/user/show/38322134-...,[119],[13],[4.27],NaN
4434,[7655754],[bec],[https://www.goodreads.com/user/show/7655754-bec],[273],[95],[4.14],[https://images.gr-assets.com/users/1374625553...
4435,[85043200],[dvora],[https://www.goodreads.com/user/show/85043200-...,[468],[6],[4.73],NaN

### 3. Load Ratings

In [15]:
df = pd.read_json('./ratings.json')
df

           userId                                             rating
0     [145704009]  [{'isbn': '1400341124', 'isbn13': '97814003411...
1       [8829118]  [{'isbn': '0812998626', 'isbn13': '97808129986...
2      [63113280]  [{'isbn': '', 'isbn13': '9781984829993', 'book...
3     [160270339]  [{'isbn': '0312642717', 'isbn13': '97803126427...
4     [103379996]  [{'isbn': '', 'isbn13': '', 'book_href': 'http...
...           ...                                                ...
1574  [107912421]  [{'isbn': '', 'isbn13': '', 'book_href': 'http...
1575  [167510184]  [{'isbn': '', 'isbn13': '', 'book_href': 'http...
1576   [92390881]  [{'isbn': '0525539727', 'isbn13': '97805255397...
1577   [63665211]  [{'isbn': '0063308312', 'isbn13': '97800633083...
1578  [125982174]  [{'isbn': '', 'isbn13': '', 'book_href': 'http...

[1579 rows x 2 columns]

In [17]:
exploded_df = df.explode('userId').reset_index(drop=True)
exploded_df = exploded_df.explode('rating').reset_index(drop=True)
exploded_df

           userId                                             rating
0       145704009  {'isbn': '1400341124', 'isbn13': '978140034112...
1       145704009  {'isbn': '1662527004', 'isbn13': '978166252700...
2       145704009  {'isbn': '1662529376', 'isbn13': '978166252937...
3       145704009  {'isbn': '1662529341', 'isbn13': '978166252934...
4       145704009  {'isbn': '166252823X', 'isbn13': '978166252823...
...           ...                                                ...
525779  125982174  {'isbn': '0439554934', 'isbn13': '978043955493...
525780  125982174  {'isbn': '0316015849', 'isbn13': '978031601584...
525781  125982174  {'isbn': '0062024035', 'isbn13': '978006202403...
525782  125982174  {'isbn': '', 'isbn13': '', 'book_href': 'https...
525783  125982174  {'isbn': '0439023483', 'isbn13': '978043902348...

[525784 rows x 2 columns]

In [19]:
expanded_df = pd.concat(
    [exploded_df.drop(columns='rating'), pd.json_normalize(exploded_df['rating'])],
    axis=1
)

In [20]:
expanded_df

,userId,isbn,isbn13,book_href,rating
0,145704009,1400341124,9781400341122,https://www.goodreads.com/book/show/200212922-...,5
1,145704009,1662527004,9781662527005,https://www.goodreads.com/book/show/219754771-...,4
2,145704009,1662529376,9781662529375,https://www.goodreads.com/book/show/220389090-...,4
3,145704009,1662529341,9781662529344,https://www.goodreads.com/book/show/220389457-...,4
4,145704009,166252823X,9781662528231,https://www.goodreads.com/book/show/220389455-...,3
...,...,...,...,...,...
525779,125982174,0439554934,9780439554930,https://www.goodreads.com/book/show/3.Harry_Po...,5
525780,125982174,0316015849,9780316015844,https://www.goodreads.com/book/show/41865.Twil...,5
525781,125982174,0062024035,9780062024039,https://www.goodreads.com/book/show/13335037-d...,5
525782,125982174,,,https://www.goodreads.com/book/show/11870085-t...,5
525783,125982174,0439023483,9780439023481,https://www.goodreads.com/book/show/2767052-th...,5

In [28]:
print(f"Unique ISBN_10: {expanded_df['isbn'].nunique()}, ISBN_13: {expanded_df['isbn13'].nunique()}")
print(f"Unique userId: {expanded_df['userId'].nunique()}")

Unique ISBN_10: 141192, ISBN_13: 143252
Unique userId: 1579